-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mylibrarydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mylibrarydb` ;

-- -----------------------------------------------------
-- Schema mylibrarydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mylibrarydb` DEFAULT CHARACTER SET utf8 ;
USE `mylibrarydb` ;

-- -----------------------------------------------------
-- Table `book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `book` ;

CREATE TABLE IF NOT EXISTS `book` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cover_url` VARCHAR(2000) NULL,
  `title` VARCHAR(100) NOT NULL,
  `description` TEXT NULL,
  `author` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NULL,
  `genre` VARCHAR(45) NULL,
  `pages` INT NULL,
  `published_year` INT NULL,
  `price` DECIMAL(6,2) NULL,
  `isbn` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SET SQL_MODE = '';
DROP USER IF EXISTS libraryuser@localhost;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'libraryuser'@'localhost' IDENTIFIED BY 'libraryuser';

GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE * TO 'libraryuser'@'localhost';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `book`
-- -----------------------------------------------------
START TRANSACTION;
USE `mylibrarydb`;
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (1, 'https://m.media-amazon.com/images/I/41Ci-WtNGWL._SY344_BO1,204,203,200_.jpg', 'No Longer Human', 'Osamu Dazai’s immortal—and supposedly autobiographical—work of Japanese literature, is perfectly adapted here into a manga by Junji Ito. The imagery wrenches open the text of the novel one line at a time to sublimate Yozo’s mental landscape into something even more delicate and grotesque. This is the ultimate in art by Ito, proof that nothing can surpass the terror of the human psyche.', 'Junji Ito', 'Japan', 'Novel', 616, 2019, 30.25, '1974707091');
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (2, 'https://m.media-amazon.com/images/I/51ihv5SnMnL._SY344_BO1,204,203,200_.jpg', 'Orthodox Study Bible', 'Commissioned in 1975 by Thomas Nelson, 130 international and multi-denominational Bible scholars, church leaders, and lay Christians worked for seven years to create a completely new, modern translation of Scripture that retained the purity and stylistic beauty of the King James Version', 'Thomas Nelson', 'United States', 'Theology', 1856, 2008, 36.49, '0718003594');
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (3, 'https://m.media-amazon.com/images/I/51wTS7XDq+L._SY344_BO1,204,203,200_.jpg', 'Silence', 'Seventeenth-century Japan: Two Portuguese Jesuit priests travel to a country hostile to their religion, where feudal lords force the faithful to publicly renounce their beliefs. Eventually captured and forced to watch their Japanese Christian brothers lay down their lives for their faith, the priests bear witness to unimaginable cruelties that test their own beliefs.', 'Shusaku Endo', 'Japan', 'Novel', 256, 1966, 12.19, '1250082242');
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (4, 'https://m.media-amazon.com/images/I/51jjZA38RgL._SX331_BO1,204,203,200_.jpg', 'Great Tales of Horror', 'Beginning with The Call of the Cthulhu, the first story of the Cthulhu Mythos, and demonstrating the highly original combination of the supernatural, horror and science fiction that was to influence generations of fantasy writers, this collection of 20 short stories by HP Lovecraft (1890-1937) presents his best-known tales, including The Dunwich Horror, The Rats in the Walls and the novella set in the wastes of Antarctica, At the Mountains of Madness.', 'H.P Lovecraft', 'United States', 'Fiction', 600, 2012, 10.49, '1435140370');
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (5, 'https://m.media-amazon.com/images/I/51RemzIhvDL._SY344_BO1,204,203,200_.jpg', 'Revolt Against the Modern World', 'With unflinching gaze and uncompromising intensity Julius Evola analyzes the spiritual and cultural malaise at the heart of Western civilization and all that passes for progress in the modern world. As a gadfly, Evola spares no one and nothing in his survey of what we have lost and where we are headed.', 'Julius Evola', 'Italy', 'Philosophy', 375, 1934, 26.68, '089281506X');
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (6, 'https://m.media-amazon.com/images/I/413HlIU9zhL._SY344_BO1,204,203,200_.jpg', 'The Republic', 'Presented in the form of a dialogue between Socrates and three different interlocutors, it is an inquiry into the notion of a perfect community and the ideal individual within it. During the conversation other questions are raised: what is goodness; what is reality; what is knowledge? The Republic also addresses the purpose of education and the role of both women and men as \"guardians\" of the people.', 'Plato', 'Greece', 'Philosophy', 416, -375, 11.70, '0140455116');
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (7, 'https://m.media-amazon.com/images/I/411-wdledbL._SY344_BO1,204,203,200_.jpg', 'Meditations', 'Written in Greek by an intellectual Roman emperor without any intention of publication, the Meditations of Marcus Aurelius  offer a wide range of fascinating spiritual reflections and exercises developed as the leader struggled to understand himself and make sense of the universe', 'Marcus Aurelius', 'Italy', 'Philosophy', 304, 1634, 9.90, '0140449337');
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (8, 'https://kbimages1-a.akamaihd.net/68229b42-3d06-4e3e-a26c-347144ee829f/353/569/90/False/the-divine-comedy-163.jpg', 'The Divine Comedy', 'Dante’s masterpiece of literature is well matched by the peerless art of Gustave Doré. Dante and his guides, Virgil and Beatrice, journey through the cantos in an allegory of the passage of the soul through the Afterlife, with the subtle engraving of Doré’s illustrations perfectly complementing the movement from darkness through to light.', 'Dante Alighieri', 'Italy', 'Fiction', 432, 1472, 30.00, '1786648113');
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (9, 'https://m.media-amazon.com/images/I/71vK0WVQ4rL._AC_UF1000,1000_QL80_.jpg', 'How to Win Friends & Influence People', 'Dale Carnegie’s rock-solid, time-tested advice has carried countless people up the ladder of success in their business and personal lives.', 'Dale Carnegie', 'United States', 'Self-help', 320, 1936, 10.30, '0671027034');
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (10, 'https://m.media-amazon.com/images/P/1250788455.01._SCLZZZZZZZ_SX500_.jpg', 'The Brothers Karamazov', 'The Brothers Karamasov is a murder mystery, a courtroom drama, and an exploration of erotic rivalry in a series of triangular love affairs involving the “wicked and sentimental” Fyodor Pavlovich Karamazov and his three sons―the impulsive and sensual Dmitri; the coldly rational Ivan; and the healthy, red-cheeked young novice Alyosha.', 'Fyodor Dostoyevsky', 'Russia', 'Fiction', 880, 1880, 16.99, '1250788455');
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (11, 'https://m.media-amazon.com/images/I/51MKJPfjq2L._SX324_BO1,204,203,200_.jpg', 'The Origins of Totalitarianism', 'his classic, definitive account of totalitarianism traces the emergence of modern racism as an \"ideological weapon for imperialism\", beginning with the rise of anti-Semitism in Europe in the 19th century and continuing through the New Imperialism period from 1884 to World War I.', 'Hannah Arendt', 'Germany', 'History', 704, 1955, 14.49, '0156701537');
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (12, 'https://m.media-amazon.com/images/I/41pK6jIGlKL._SX330_BO1,204,203,200_.jpg', 'Homage to Catalonia', 'In 1936, originally intending merely to report on the Spanish Civil War as a journalist, George Orwell found himself embroiled as a participant—as a member of the Workers’ Party of Marxist Unity. Fighting against the Fascists, he described in painfully vivid and occasionally comic detail life in the trenches—with a “democratic army” composed of men with no ranks, no titles, and often no weapons—and his near fatal wounding. As the politics became tangled, Orwell was pulled into a heartbreaking conflict between his own personal ideals and the complicated realities of political power struggles.', 'George Orwell', 'Spain', 'Non-Fiction', 304, 1938, 10.89, '0544382048');
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (13, 'https://m.media-amazon.com/images/I/41f+CKvPEpL._SX258_BO1,204,203,200_.jpg', '1984', 'n 1984, London is a grim city in the totalitarian state of Oceania where Big Brother is always watching you and the Thought Police can practically read your mind. Winston Smith is a man in grave danger for the simple reason that his memory still functions. Drawn into a forbidden love affair, Winston finds the courage to join a secret revolutionary organization called the Brotherhood, dedicated to the destruction of the Party. Together with his beloved Julia, he hazards his life in a deadly match against the powers that be.', 'George Orwell', 'England', 'Fiction', 224, 1949, 18.49, '0358359929');
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (14, 'https://m.media-amazon.com/images/I/61QIZw3MOoL._SY344_BO1,204,203,200_.jpg', 'The Doors of Perception', 'Among the most profound and influential explorations of mind-expanding psychedelic drugs ever written, here are two complete classic books—The Doors of Perception and Heaven and Hell—in which Aldous Huxley, author of Brave New World, reveals the mind\'s remote frontiers and the unmapped areas of human consciousness. This edition also features an additional essay, \"Drugs That Shape Men\'s Minds,\" now included for the first time.', 'Aldous Huxley', 'England', 'Auto-Biography', 208, 1954, 14.99, '0061729078');
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (15, 'https://m.media-amazon.com/images/I/41SokAY5GmL.jpg', 'Lenin: The Man, the Dictator, and the Master of Terror', 'Sebestyen reveals Lenin as a ruthless and single-minded despot and a \"product of his time and place: a violent, tyrannical and corrupt Russia\". He seized power in a coup, promised a revolution, a socialist utopia for the people, offered simple solutions to complex issues, and constantly lied; in fact what he created was more \"a mirror image of the Romanov autocracy\". He authorized the deaths of thousands of people and created a system based on the idea that political terror against opponents was justified for the greater ideal. One of his old comrades who had once admired him said he \"desired the good...but created evil\". And that would include his invention of Stalin, who would take Lenin\'s system of the gulag and the secret police to new heights.', 'Victor Sebestyen', 'Hungary', 'History', 592, 2017, 22.66, '1101871636');
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (16, 'https://m.media-amazon.com/images/I/51kRWJZ97pL._SX331_BO1,204,203,200_.jpg', 'Utopia', 'In his most famous and controversial book, Utopia, Thomas More imagines a perfect island nation where thousands live in peace and harmony, men and women are both educated, and all property is communal. Through dialogue and correspondence between the protagonist Raphael Hythloday and his friends and contemporaries, More explores the theories behind war, political disagreements, social quarrels, and wealth distribution and imagines the day-to-day lives of those citizens enjoying freedom from fear, oppression, violence, and suffering.', 'Sir Thomas More', 'England', 'Fiction', 176, 1516, 11.99, '9780140449105');
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (17, 'https://m.media-amazon.com/images/I/510RH1nJgQL._SY344_BO1,204,203,200_.jpg', 'Letters from a Stoic', 'For several years of his turbulent life, Seneca was the guiding hand of the Roman Empire. His inspired reasoning derived mainly from the Stoic principles, which had originally been developed some centuries earlier in Athens. This selection of Seneca\'s letters shows him upholding the austere ethical ideals of Stoicism—the wisdom of the self-possessed person immune to overmastering emotions and life’s setbacks—while valuing friendship and the courage of ordinary men, and criticizing the harsh treatment  of slaves and the cruelties in the gladiatorial arena. The humanity and wit revealed in Seneca’s interpretation of Stoicism is a moving and inspiring declaration of the dignity of the individual mind.', 'Seneca', 'Italy', 'Philosophy', 254, 64, 13.99, '9780140442106');
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (18, 'https://m.media-amazon.com/images/I/41-n-3hZMeL._SY344_BO1,204,203,200_.jpg', 'Brave New World', 'Aldous Huxley\'s profoundly important classic of world literature, Brave New World is a searching vision of an unequal, technologically-advanced future where humans are genetically bred, socially indoctrinated, and pharmaceutically anesthetized to passively uphold an authoritarian ruling order–all at the cost of our freedom, full humanity, and perhaps also our souls.', 'Aldous Huxley', 'England', 'Fiction', 288, 1932, 11.47, '0060850523');
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (19, 'https://m.media-amazon.com/images/I/41K1QqtKyNL._SY344_BO1,204,203,200_.jpg', 'The Idiot', 'After his great portrayal of a guilty man in Crime and Punishment, Dostoevsky set out in The Idiot to portray a man of pure innocence. The twenty-six-year-old Prince Myshkin, following a stay of several years in a Swiss sanatorium, returns to Russia to collect an inheritance and “be among people.” Even before he reaches home he meets the dark Rogozhin, a rich merchant’s son whose obsession with the beautiful Nastasya Filippovna eventually draws all three of them into a tragic denouement. In Petersburg the prince finds himself a stranger in a society obsessed with money, power, and manipulation. Scandal escalates to murder as Dostoevsky traces the surprising effect of this “positively beautiful man” on the people around him, leading to a final scene that is one of the most powerful in all of world literature.', 'Fyodor Dostoyevsky', 'Russia', 'Fiction', 656, 1868, 16.29, '0375702245');
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (20, 'https://m.media-amazon.com/images/I/41novGr34wL._SY344_BO1,204,203,200_.jpg', 'Notes from Underground', 'One of the most remarkable characters in literature, the unnamed narrator of Dostoevsky\'s most revolutionary novel is a former official who has defiantly withdrawn into an underground existence. In full retreat from society, he scrawls a passionate, obsessive, self-contradictory narrative that serves as a devastating attack on social utopianism and an assertion of man’s essentially irrational nature.', 'Fyodor Dostoyevsky', 'Russia', 'Fiction', 136, 1864, 12.54, '067973452X');
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (21, 'https://m.media-amazon.com/images/I/41WYXBA5mrL._SX320_BO1,204,203,200_.jpg', 'Crime and Punishment', 'When Raskolnikov, an impoverished student living in the St. Petersburg of the tsars, commits an act of murder and theft, he sets into motion a story that is almost unequalled in world literature for its excruciating suspense, its atmospheric vividness, and its depth of characterization and vision. Dostoevsky’s drama of sin, guilt, and redemption transforms the sordid story of an old woman’s murder into the nineteenth century’s profoundest and most compelling philosophical novel.', 'Fyodor Dostoyevsky', 'Russia', 'Fiction', 565, 1866, 15.99, '0679734503');
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (22, 'https://m.media-amazon.com/images/I/41MQggAwO8L._SX328_BO1,204,203,200_.jpg', 'The Gulag Archipelago', 'The Gulag Archipelago is an exhaustive and compelling account based on Solzhenitsyn’s own eight years in Soviet prison camps, on other prisoners’ stories committed to his photographic memory while in detention, and on letters and historical sources. The work represents the author’s attempt to compile a literary and historical record of the Soviet regime’s comprehensive but deeply irrational use of terror against its own population. A testimonial to Stalinist atrocities, The Gulag Archipelago devastated readers outside the Soviet Union with its descriptions of the brutality of the Soviet regime.', 'Aleksandr Solzhenitsyn', 'Russia', 'History', 701, 1973, 13.99, '9780061253713');
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (23, 'https://m.media-amazon.com/images/I/51uSVURMnVL._SY344_BO1,204,203,200_.jpg', 'The Count of Monte Cristo', 'This beloved novel tells the story of Edmond Dantès, wrongfully imprisoned for life in the supposedly impregnable sea fortress, the Château d’If. After a daring escape, and after unearthing a hidden treasure revealed to him by a fellow prisoner, he devotes the rest of his life to tracking down and punishing the enemies who wronged him.', 'Alexandre Dumas', 'France', 'Fiction', 1240, 1846, 29.07, '0307271129');
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (24, 'https://m.media-amazon.com/images/I/514cSQ0O9OL._SX258_BO1,204,203,200_.jpg', 'Python Crash Course, 3rd Edition', 'Python Crash Course is the world’s best-selling guide to the Python programming language. This fast-paced, thorough introduction will have you writing programs, solving problems, and developing functioning applications in no time.', 'Eric Matthes', 'United States', 'Programming', 552, 2022, 40.49, '1718502702');
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (25, 'https://m.media-amazon.com/images/I/41FBtYZ8AfS._SX384_BO1,204,203,200_.jpg', 'Alif Baa', 'Alif Baa is the first volume of the best-selling Al-Kitaab Arabic Language Program, now in its third edition. In this edition of Alif Baa: Introduction to Arabic Letters and Sounds with Website, English-speaking students will use the integrated method of learning colloquial and formal (spoken and written) Arabic together. Alif Baa provides learners with all the material necessary to learn the sounds of Arabic, write its letters, and begin speaking Arabic.The accompanying companion website―included with the book―offers fully integrated exercises to use alongside the text.', 'Mahmoud Al-Batal', 'Lebanon', 'Language', 272, 2021, 14.94, '1647121817');
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (26, 'https://m.media-amazon.com/images/I/31c4U69DLDL._SY344_BO1,204,203,200_.jpg', 'Paradise Lost', 'Paradise Lost is an epic poem in blank verse by the 17th-century English poet John Milton (1608–1674). It is considered to be Milton\'s major work, and it helped solidify his reputation as one of the greatest English poets of his time. The poem concerns the biblical story of the Fall of Man: the temptation of Adam and Eve by the fallen angel Satan and their expulsion from the Garden of Eden. Milton\'s purpose, as stated in Book I, is to \"justify the ways of God to men.\"', 'John Milton', 'England', 'Fiction', 205, 1667, 7.99, '979-8670888615');
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (27, 'https://m.media-amazon.com/images/I/41rEDgMC6-L._SY344_BO1,204,203,200_.jpg', 'The Order of Time', 'Why do we remember the past and not the future? What does it mean for time to \"flow\"? Do we exist in time or does time exist in us? In lyric, accessible prose, Carlo Rovelli invites us to consider questions about the nature of time that continue to puzzle physicists and philosophers alike.\n\nFor most readers this is unfamiliar terrain. We all experience time, but the more scientists learn about it, the more mysterious it remains. We think of it as uniform and universal, moving steadily from past to future, measured by clocks. Rovelli tears down these assumptions one by one, revealing a strange universe where at the most fundamental level time disappears. He explains how the theory of quantum gravity attempts to understand and give meaning to the resulting extreme landscape of this timeless world.', 'Carlo Rovelli', 'Italy', 'Physics', 256, 2019, 11.39, '0735216118');
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (28, 'https://m.media-amazon.com/images/I/41fIOsug3PL._SY344_BO1,204,203,200_.jpg', 'Ubik', 'Named one of Time\'s 100 Best Books, Ubik is a mind-bending, classic novel about the perception of reality from Philip K. Dick, the Hugo Award-winning author of The Man in the High Castle. “From the stuff of space opera, Dick spins a deeply unsettling existential horror story, a nightmare you’ll never be sure you’ve woken up from.”—Lev Grossman, Time Glen Runciter runs a lucrative business — deploying his teams of anti-psychics to corporate clients who want privacy and security from psychic spies. But when he and his top team are ambushed by a rival, he is gravely injured and placed in “half-life,” a dreamlike state of suspended animation. Soon, though, the surviving members of the team begin experiencing some strange phenomena, such as Runciter’s face appearing on coins and the world seeming to move backward in time.', 'Philip K. Dick', 'United States', 'Science Fiction', 240, 1969, 11.99, '0547572298');
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (29, 'https://m.media-amazon.com/images/I/51kDq26MsEL._SY344_BO1,204,203,200_.jpg', 'The Maltese Falcon', 'A treasure worth killing for. Sam Spade, a slightly shopworn private eye with his own solitary code of ethics. A perfumed grafter named Joel Cairo, a fat man name Gutman, and Brigid O’Shaughnessy, a beautiful and treacherous woman whose loyalties shift at the drop of a dime. These are the ingredients of Dashiell Hammett\'s iconic, influential, and beloved The Maltese Falcon.', 'Dashiell Hammett', 'United States', 'Fiction', 217, 1929, 14.49, '0679722645');
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (30, 'https://m.media-amazon.com/images/I/51OjtMiKQTL._SX328_BO1,204,203,200_.jpg', 'Food of the Gods: The Search for the Original Tree of Knowledge', 'Why, as a species, are humans so fascinated by altered states of consciousness? Can altered states reveal something to us about our origins and our place in nature? In Food of the Gods, ethnobotanist Terence McKenna’s research on man’s ancient relationship with chemicals opens a doorway to the divine, and perhaps a solution for saving our troubled world. McKenna provides a revisionist look at the historical role of drugs in the East and the West, from ancient spice, sugar, and rum trades to marijuana, cocaine, synthetics, and even television—illustrating the human desire for the “food of the gods” and the powerful potential to replace abuse of illegal drugs with a shamanic understanding, insistence on community, reverence for nature, and increased self-awareness.', 'Terrence McKenna', 'United States', 'Anthropology', 311, 1993, 17.99, '0553371304');
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (31, 'https://m.media-amazon.com/images/I/51yoHjJDQ3L._SY344_BO1,204,203,200_.jpg', 'Extreme Ownership', 'Combat, the most intense and dynamic environment imaginable, teaches the toughest leadership lessons, with absolutely everything at stake. Jocko Willink and Leif Babin learned this reality first-hand on the most violent and dangerous battlefield in Iraq. As leaders of SEAL Team Three’s Task Unit Bruiser, their mission was one many thought impossible: help U.S. forces secure Ramadi, a violent, insurgent-held city deemed “all but lost.” In gripping, firsthand accounts of heroism, tragic loss, and hard-won victories, they learned that leadership―at every level―is the most important factor in whether a team succeeds or fails.', 'Jocko Willink', 'United States', 'Self-help', 384, 2017, 17.99, '9781250183866');
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (32, 'https://m.media-amazon.com/images/I/41oGA1RNwXL._SY344_BO1,204,203,200_.jpg', 'Arabic Stories for Language Learners: Traditional Middle Eastern Tales In Arabic and English', 'The traditional stories of a country are invaluable at providing insight into understanding the culture, history and language of a people. A great way to learn Arabic, the sixty-six stories found in Arabic Stories for Language Learners present the vocabulary and grammar used every day in Arabic-speaking countries. Pulled from a wide variety of sources that have been edited and simplified for learning purposes, these stories are presented in parallel Arabic and English, facilitating language learning in the classroom and via self-study. Each story is followed by a series of questions in Arabic and English to test comprehension and encourage discussion.', 'Hezi Brosh', 'United States', 'Language', 256, 2013, 19.95, '0804843007');
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (33, 'https://m.media-amazon.com/images/I/414yS8wldNL._SY344_BO1,204,203,200_.jpg', 'Beyond Good and Evil', 'Beyond Good and Evil: Prelude to a Philosophy of the Future is a book by philosopher Friedrich Nietzsche, first published in 1886. It draws on and expands the ideas of his previous work, Thus Spoke Zarathustra, but with a more critical and polemical approach. In Beyond Good and Evil, Nietzsche accuses past philosophers of lacking critical sense and blindly accepting dogmatic premises in their consideration of morality. Specifically, he accuses them of founding grand metaphysical systems upon the faith that the good man is the opposite of the evil man, rather than just a different expression of the same basic impulses that find more direct expression in the evil man. The work moves into the realm \"beyond good and evil\" in the sense of leaving behind the traditional morality which Nietzsche subjects to a destructive critique in favour of what he regards as an affirmative approach that fearlessly confronts the perspectival nature of knowledge and the perilous condition of the modern individual.', 'Friedrick Nietzsche', 'Germany', 'Psychology', 116, 1886, 6.99, '9781503250888');
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (34, 'https://m.media-amazon.com/images/I/51WcKZ4NQPL._SY344_BO1,204,203,200_.jpg', 'The Lucifer Effect: Understanding How Good People Turn Evil', 'Renowned social psychologist and creator of the Stanford Prison Experiment Philip Zimbardo explores the mechanisms that make good people do bad things, how moral people can be seduced into acting immorally, and what this says about the line separating good from evil.\n\nThe Lucifer Effect explains how—and the myriad reasons why—we are all susceptible to the lure of “the dark side.” Drawing on examples from history as well as his own trailblazing research, Zimbardo details how situational forces and group dynamics can work in concert to make monsters out of decent men and women. ', 'Philip Zimbardo', 'United States', 'Psychology', 576, 2008, 17.99, '0812974441');
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (35, 'https://m.media-amazon.com/images/I/51dxRfIejrL._SY344_BO1,204,203,200_.jpg', 'Sleeping Giants', 'A girl named Rose is riding her new bike near her home in Deadwood, South Dakota, when she falls through the earth. She wakes up at the bottom of a square hole, its walls glowing with intricate carvings. But the firemen who come to save her peer down upon something even stranger: a little girl in the palm of a giant metal hand.\n\nSeventeen years later, the mystery of the bizarre artifact remains unsolved—its origins, architects, and purpose unknown. Its carbon dating defies belief; military reports are redacted; theories are floated, then rejected.\n\nBut some can never stop searching for answers.', 'Sylvain Neuvel', 'Canada', 'Fiction', 336, 2017, 16.73, '1101886714');
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (36, 'https://m.media-amazon.com/images/I/51dU1i1+AiL._SX331_BO1,204,203,200_.jpg', 'Boyd: The Fighter Pilot Who Changed the Art of War', 'John Boyd may be the most remarkable unsung hero in all of American military history. Some remember him as the greatest U.S. fighter pilot ever -- the man who, in simulated air-to-air combat, defeated every challenger in less than forty seconds. Some recall him as the father of our country\'s most legendary fighter aircraft -- the F-15 and F-16. Still others think of Boyd as the most influential military theorist since Sun Tzu. They know only half the story.', 'Robert Coram', 'United States', 'History', 504, 2004, 19.99, '0316796883');
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (37, 'https://m.media-amazon.com/images/I/41lZKXt1+ML._SY344_BO1,204,203,200_.jpg', 'Sapiens: A Brief History of Humankind', 'From examining the role evolving humans have played in the global ecosystem to charting the rise of empires, Sapiens integrates history and science to reconsider accepted narratives, connect past developments with contemporary concerns, and examine specific events within the context of larger ideas. Dr. Harari also compels us to look ahead, because over the last few decades humans have begun to bend laws of natural selection that have governed life for the past four billion years. We are acquiring the ability to design not only the world around us, but also ourselves. Where is this leading us, and what do we want to become?', 'Yuval Noah Harari', 'Israel', 'Anthropology', 578, 2018, 15.00, '9780062316110');
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (38, 'https://m.media-amazon.com/images/I/4169yIOsEaL._SY344_BO1,204,203,200_.jpg', 'Alone: A Classic Polar Adventure', 'When Admiral Richard E. Byrd set out on his second Antarctic expedition in 1934, he was already an international hero for having piloted the first flights over the North and South Poles. His plan for this latest adventure was to spend six months alone near the bottom of the world, gathering weather data and indulging his desire “to taste peace and quiet long enough to know how good they really are.” But early on things went terribly wrong. Isolated in the pervasive polar night with no hope of release until spring, Byrd began suffering inexplicable symptoms of mental and physical illness. By the time he discovered that carbon monoxide from a defective stovepipe was poisoning him, Byrd was already engaged in a monumental struggle to save his life and preserve his sanity.', 'Richard Evelyn Byrd', 'United States', 'History', 310, 2003, 35.00, '1559634634');
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (39, 'https://m.media-amazon.com/images/I/31gHMQMqCAL._SY344_BO1,204,203,200_.jpg', 'The Prince', 'The Prince is a 16th-century political treatise written by Italian diplomat and political theorist Niccolò Machiavelli as an instruction guide for new princes and royals. The general theme of The Prince is of accepting that the aims of princes – such as glory and survival – can justify the use of immoral means to achieve those ends.', 'Niccolo Machiavelli', 'Italy', 'Politics', 114, 1532, 7.99, '979-8712157877');
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (40, 'https://m.media-amazon.com/images/I/41UK+xizvyL._SY344_BO1,204,203,200_.jpg', 'Bullets and Opium: Real-Life Stories of China After the Tiananmen Square Massacre', 'Much has been written about the Tiananmen Square protests, but very little exists in the words of those who were actually there.\n\nFor over seven years, Liao Yiwu—a master of contemporary Chinese literature, imprisoned and persecuted as a counter-revolutionary until he fled the country in 2011—secretly interviewed survivors of the devastating 1989 Tiananmen Square massacre. Tortured, imprisoned, and forced into silence and the margins of Chinese society for thirty years, their harrowing and unforgettable stories are now finally revealed in this “indispensable historical document” (Kirkus Reviews, starred review).', 'Liao Yiwu', 'China', 'History', 320, 2012, 16.94, '1982126655');
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (41, 'https://m.media-amazon.com/images/I/41+IcE1BGXL._SY344_BO1,204,203,200_.jpg', 'The Iliad', 'Dating to the ninth century B.C., Homer’s timeless poem still vividly conveys the horror and heroism of men and gods wrestling with towering emotions and battling amidst devastation and destruction, as it moves inexorably to the wrenching, tragic conclusion of the Trojan War. Renowned classicist Bernard Knox observes in his superb introduction that although the violence of the Iliad is grim and relentless, it coexists with both images of civilized life and a poignant yearning for peace.', 'Homer', 'Greece', 'Fiction', 704, -900, 12.99, '9780140275360');
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (42, 'https://m.media-amazon.com/images/I/51raOBsi-CL._SY344_BO1,204,203,200_.jpg', 'The Tibetan Book of the Dead', 'Translated with the close support of leading contemporary masters and hailed as “a tremendous accomplishment,” this book faithfully presents the insights and intentions of the original work. It includes one of the most detailed and compelling descriptions of the after-death state in world literature, practices that can transform our experience of daily life, guidance on helping those who are dying, and an inspirational perspective on coping with bereavement.', 'Padmasambhava', 'Pakistan', 'Theology', 535, 750, 21.49, '0143104942');
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (43, 'https://m.media-amazon.com/images/I/512g4Ejpt7L._SY344_BO1,204,203,200_.jpg', 'Das Kapital', 'Das Kapital is a revolutionary book; forged during the political and industrial revolutions of the nineteenth century, it became the keystone of many Communist revolutions of the twentieth century. In this comprehensive analysis of capitalist economics and articulation of his theory of class conflict, Karl Marx (1818-1883) relentlessly argues that the accumulation of capital can only be achieved by bourgeoisie exploitation of the working classes. Das Kapital has not only changed history, but also human thought, becoming a foundational text in materialist philosophy, economics and politics.', 'Karl Marx', 'Russia', 'Politics', 594, 1867, 29.99, '1789430658');
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (44, 'https://m.media-amazon.com/images/I/3148SDQf4XL._SY344_BO1,204,203,200_.jpg', 'The Archaeology of Knowledge: And the Discourse on Language', 'The Archaeology of Knowledge begins at the level of \"things aid\" and moves quickly to illuminate the connections between knowledge, language, and action in a style at once profound and personal. A summing up of Foucault\'s own methodological assumptions, this book is also a first step toward a genealogy of the way we live now.', 'Michel Foucault', 'France', 'Philosophy', 256, 1972, 17.00, '9780394711065');
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (45, 'https://m.media-amazon.com/images/I/419G6JyTj-L._SX331_BO1,204,203,200_.jpg', 'Being and Nothingness', 'In 1943, Jean-Paul Sartre published his masterpiece, Being and Nothingness, and laid the foundation of his legacy as one of the greatest twentieth century philosophers. A brilliant and radical account of the human condition, Being and Nothingness explores what gives our lives significance.\n\nIn a new and more accessible translation, this foundational text argues that we alone create our values and our existence is characterized by freedom and the inescapability of choice. Far from being an internal, passive container for our thoughts and experiences, human consciousness is constantly projecting itself into the outside world and imbuing it with meaning.', 'Jean-Paul Sartre', 'France', 'Philosophy', 928, 1943, 16.79, '1982105453');
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (46, 'https://m.media-amazon.com/images/I/415tB5UC7IL._SY344_BO1,204,203,200_.jpg', 'The Metamorphosis', 'Metamorphosis is a novella written by Franz Kafka which was first published in 1915. One of Kafka\'s best-known works, The Metamorphosis tells the story of salesman Gregor Samsa who wakes one morning to find himself inexplicably transformed into a huge insect, subsequently struggling to adjust to this new condition. The novella has been widely discussed among literary critics, with differing interpretations being offered.', 'Franz Kafka', 'Austria', 'Fiction', 52, 1915, 4.99, '1680920715');
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (47, 'https://m.media-amazon.com/images/I/517eqjeVDzL._SY344_BO1,204,203,200_.jpg', 'The Stranger', 'Behind the subterfuge, Camus explores what he termed \"the nakedness of man faced with the absurd\" and describes the condition of reckless alienation and spiritual exhaustion that characterized so much of twentieth-century life. \n\n“The Stranger is a strikingly modern text and Matthew Ward’s translation will enable readers to appreciate why Camus’s stoical anti-hero and ­devious narrator remains one of the key expressions of a postwar Western malaise, and one of the cleverest exponents of a literature of ambiguity.” –from the Introduction by Peter Dunwoodie', 'Albert Camus', 'French', 'Fiction', 123, 1942, 13.50, '9780679720201');
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (48, 'https://m.media-amazon.com/images/I/51z6huzmB9L._SY344_BO1,204,203,200_.jpg', 'The Trial', 'Written in 1914, The Trial is the terrifying tale of Josef K., a respectable bank officer who is suddenly and inexplicably arrested and must defend himself against a charge about which he can get no information. Whether read as an existential tale, a parable, or a prophecy of the excesses of modern bureaucracy wedded to the madness of totalitarianism, Kafka\'s nightmare has resonated with chilling truth for generations of readers. This new edition is based upon the work of an international team of experts who have restored the text, the sequence of chapters, and their division to create a version that is as close as possible to the way the author left it.', 'Franz Kafka', 'Austria', 'Fiction', 304, 1914, 14.36, '9780805209990');
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (49, 'https://m.media-amazon.com/images/I/51Ni04O2s4L._SX318_BO1,204,203,200_.jpg', 'The Wretched of the Earth', 'First published in 1961, and reissued in this sixtieth anniversary edition with a powerful new introduction by Cornel West, Frantz Fanon’s The Wretched of the Earth is a masterfuland timeless interrogation of race, colonialism, psychological trauma, and revolutionary struggle, and a continuing influence on movements from Black Lives Matter to decolonization. A landmark text for revolutionaries and activists, The Wretched of the Earth is an eternal touchstone for civil rights, anti-colonialism, psychiatric studies, and Black consciousness movements around the world. Alongside Cornel West’s introduction, the book features critical essays by Jean-Paul Sartre and Homi K. Bhabha. This sixtieth anniversary edition of Fanon’s most famous text stands proudly alongside such pillars of anti-colonialism and anti-racism as Edward Said’s Orientalism and The Autobiography of Malcolm X.', 'Fanon Frantz', 'United States', 'Politics', 336, 1961, 12.69, '0802158633');
INSERT INTO `book` (`id`, `cover_url`, `title`, `description`, `author`, `country`, `genre`, `pages`, `published_year`, `price`, `isbn`) VALUES (50, 'https://m.media-amazon.com/images/I/416ASRyA6UL._SX331_BO1,204,203,200_.jpg', 'Mine Were of Trouble: A Nationalist Account of the Spanish Civil War', 'Spain, 1936. Escalating violence between left- and right-wing political factions boils over. Military officers stage a coup against a democratically elected, Soviet-backed, government. The country is thrown into chaos as centuries-old tensions return to the forefront. Hundreds of thousands of Spaniards choose sides and engage in the most devastating combat since the First World War. For loyalists to the Republic, the fight is seen as one for equality and their idea of progress. For the rebels, the struggle is a preemptive strike by tradition against an attempted communist takeover.\n\nThousands of foreigners, too, join the struggle. Most fight with the Soviet-sponsored International Brigades or other militias aligned with the loyalist “Republicans”. Only a few side with the rebel “Nationalists”. One of these rare volunteers for the Nationalists was Peter Kemp, a young British law student. Kemp, despite having little training or command of the Spanish language, was moved by the Nationalist struggle against international Communism. Using forged documents, he sneaked into Spain and joined a traditionalist militia, the Requetés, with which he saw intense fighting. Later, he volunteered to join the legendary and ruthless Spanish Foreign Legion, where he distinguished himself with heroism. Because of this bravery, he was one of the few foreign volunteers granted a private audience with Generalissimo Francisco Franco.', 'Peter Kemp', 'England', 'History', 171, 1936, 9.99, '979-8624731721');

COMMIT;

